version: '3'

services:
  app:
    build:
      context: node
    entrypoint: wait-for db:3306 -t 20 -- docker-entrypoint.sh
    command: ["node", "index.js"]
    networks:
      - node-network 
    volumes:
      - ./node:/usr/src/app
    tty: true
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - "node-network"
  nginx:
    build:
      context: nginx
    networks:
      - node-network 
    tty: true
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
